TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devagilentHPE3631A.db
DB_INSTALLS += $(TOP)/agilentHPE3631ASup/devagilentHPE3631A.proto

#=======================================
include $(TOP)/configure/RULES
